# Generated by Django 4.2 on 2023-04-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogger", name="email",),
    ]
