# Generated by Django 4.2 on 2023-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogger_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogger",
            name="bio",
            field=models.TextField(max_length=1000, verbose_name="Biography"),
        ),
    ]
