# Generated by Django 4.2 on 2023-04-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_options_alter_comment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-date", "post"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-date", "title"],
                "permissions": (("can_post", "Write a post"),),
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog",
                to="blog.blogger",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True, help_text="Enter post title", max_length=255, null=True
            ),
        ),
    ]
