# Generated by Django 4.2 on 2023-04-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["date", "post"]},
        ),
    ]
