# Generated by Django 4.2 on 2023-04-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["date", "post"],
                "permissions": (("can_delete_comment", "Delete comment"),),
            },
        ),
    ]
